### ISSUE TITLE
Merge data

### ISSUE THREAD

**Issue by ghost** [lohanidamodar/flutter_firebase_helpers#5]
The updateData function overwrites database item instead of merging changes.

**Comment by lohanidamodar** [comment]
Hey it should not, I am using the underlying `update` function which will merge the changes not overrite. check the source here
https://github.com/lohanidamodar/flutter_firebase_helpers/blob/408f756d891b41907f651f37afde3a1d3e56c185/lib/src/firestore_service.dart#L294
